# Generated by Django 3.1.5 on 2021-02-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
